# Generated by Django 3.2.9 on 2021-12-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('M', 'Morning'), ('O', 'Noon'), ('E', 'Evening')], default='M', max_length=1)),
                ('shell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shell')),
            ],
        ),
    ]
